class Peep < ActiveRecord::Base
end


__END__

Model magic: executed at runtime 

DB:
  table: peeps
  columns(table definition): id, body, created_at, updated_at
  # created_at and updated_at added by time stamps and these two
  # columns are automatically managed by ActiveRecord

  ActiveRecord now has a class called Peep which is generated by
  $rails g model peep...

  When the model is generated by rails this is what happens: 
  Peep.pluralize => Peeps.downcase => peeps => connect to db
  
  Once connected to the db ActiveRecord:
  -looks for table peeps
  -inpsects table definition(columns) and uses column names as attr_accessors
  -adds some other methods to the Peep class (to access/modify data)

All active record methods will be generated at runtime which is why there's no methods
visible in the model. 



